### ISSUE TITLE
DOC: Expand contribution guide?

### ISSUE THREAD

**Issue by pllim** [spacetelescope/stsci-package-template#13]
Currently in `CONTRIBUTING.md`, "New to github or open source projects? If you are unsure about where to start or haven't used github before, please feel free to contact the package maintainers."

Seems very vague. Perhaps we should introduce a more formal guide like http://astropy.readthedocs.io/en/latest/#developer-documentation but tailored to our org, and probably don't need to be so detailed.

**Comment by sosey** [comment]
There is an extremely wide range of packages on github for the spacetelescope organization, all possibly following different development methods.  Making something more specific at this level is something that should be left to DSMO or other management.
