### ISSUE TITLE
create template for non-python based repositories

### ISSUE THREAD

**Issue by sosey** [spacetelescope/stsci-package-template#17]
Should we have a template that's not specifically for stsci python packages?  Java, Fortran, C/C++, 
these are also used at the institute and not always in conjunction with python. Layouts for these types of packages are not always common, but they should contain the common stsci files like the CoC, licenses, some form of testing infrastructure.

I think it should be possible to  prompt for a language during a cookiecutter call, and build appropriately, skipping all the python specific file additions.

**Comment by sosey** [comment]
by people, do you mean jay? ;)

**Comment by pllim** [comment]
I'm not judging! Just curious. All the Fortran I came across was inherited. 😅

**Comment by pllim** [comment]
No one has asked for one since this was opened. Closing as won't fix.
