### ISSUE TITLE
cookiecutter: Improve the questions being asked

### ISSUE THREAD

**Issue by stscicrawford** [spacetelescope/stsci-package-template#18]
Asked by @sosey in #16 

The questions presented by the cookiecutter wont make immediate sense to new and possibly intermediate users, the readme should either point to documentation that explains each of the questions and what they mean, or include descriptions of them in the readme itself. The users should see them before running cookiecutter so they understand. Minimally include a link to the QUESTIONS.rst that has some descriptions.

I'm referring to the questions asked during setup:

Select license:
1 - Aura
2 - BSD 3-Clause
3 - GNU GPL v3+
4 - Apache Software Licence 2.0
5 - BSD 2-Clause
6 - Other
project_url [http://stsci.edu]: 
project_version [0.0.dev]: 
include_example_code [y]: 
include_example_cython_code [n]: 
include_cextern_folder [n]: 
edit_on_github_extension [False]: 
github_project [spacetelescope/stsci-package-template]:
use_travis_ci [y]: 
use_appveyor_ci [n]: 
use_read_the_docs [y]: 
sphinx_theme [stsci_rtd_theme]: 
initialize_git_repo [y]: 
Select minimum_python_version:
1 - 3.7
2 - 3.6
3 - 3.5
Choose from 1, 2, 3 [1]: 
astropy_helpers_version [v3.0.2]:

**Comment by pllim** [comment]
Looks like cookiecutter is not used here. And also probably unnecessary given https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/creating-a-template-repository
