### ISSUE TITLE
DOC: No documentation on enabling astropy-helpers

### ISSUE THREAD

**Issue by stsci-hack** [spacetelescope/stsci-package-template#19]
The use of 'cookiecutter' with this template sets up use of astropy-helpers for the new package.  However, additional steps are needed after running 'cookiecutter' in order to successfully use astropy-helpers in the installation of the package, and this information is not in any obvious location (if it even exists at all).  

A step-by-step guide showing how to use 'cookiecutter' with this template and how to use git commands to enable/integrate astropy-helpers into the package would help users successfully use this template and start developing their package efficiently.

**Comment by pllim** [comment]
I think the point of *this* template is that it doesn't want dependency on `astropy-helpers`. If you want `astropy-helpers`, it is better to use https://github.com/astropy/package-template . FYI.

**Comment by pllim** [comment]
As per [APE 17](https://github.com/astropy/astropy-APEs/blob/master/APE17.rst), there is no longer a need for `astropy-helpers`.
