### ISSUE TITLE
Add actual CITATION?

### ISSUE THREAD

**Issue by pllim** [spacetelescope/stsci-package-template#4]
CITATION appears to be empty.

**Comment by sosey** [comment]
IF you have suggestions for general text I'm open, I put that there so that people can specify how they want their package cited.

**Comment by pllim** [comment]
My suggestion is along the line of https://swcarpentry.github.io/git-novice/12-citation/ . What do you think?

**Comment by sosey** [comment]
I was thinking something more inline with this:

http://journals.aas.org/authors/references.html#Software

but there are a lot of different types of software going up on spacetelescope/, so I'm not sure what the best general thing to put here is.  I'd also like to suggest people put zenodo doi's on their repos when they are ready

**Comment by pllim** [comment]
Yeah, a link to instructions would be sufficient IMHO. If the software has accompanying paper (like Astropy), people would naturally cite the published paper instead of just as "software".
